; Decompressed graphics includes for ModRetro Tetris
; Generated by extract_all_compressed_graphics.py

Graphics_00_15CA:
    ; Original: Bank $00 offset $0015CA
    ; 96 tiles (1543 bytes)
    INCBIN "gfx/bank_00_0015CA.png"

Graphics_00_15DE:
    ; Original: Bank $00 offset $0015DE
    ; 96 tiles (1545 bytes)
    INCBIN "gfx/bank_00_0015DE.png"

Graphics_00_15F2:
    ; Original: Bank $00 offset $0015F2
    ; 96 tiles (1536 bytes)
    INCBIN "gfx/bank_00_0015F2.png"

Graphics_00_1606:
    ; Original: Bank $00 offset $001606
    ; 96 tiles (1550 bytes)
    INCBIN "gfx/bank_00_001606.png"

Graphics_00_3223:
    ; Original: Bank $00 offset $003223
    ; 64 tiles (1024 bytes)
    INCBIN "gfx/bank_00_003223.png"

Graphics_00_3277:
    ; Original: Bank $00 offset $003277
    ; 48 tiles (776 bytes)
    INCBIN "gfx/bank_00_003277.png"

Graphics_00_329F:
    ; Original: Bank $00 offset $00329F
    ; 48 tiles (768 bytes)
    INCBIN "gfx/bank_00_00329F.png"

Graphics_02_401A:
    ; Original: Bank $02 offset $00801A
    ; 1440 tiles (23045 bytes)
    INCBIN "gfx/bank_02_00801A.png"

Graphics_02_4026:
    ; Original: Bank $02 offset $008026
    ; 1440 tiles (23044 bytes)
    INCBIN "gfx/bank_02_008026.png"

Graphics_02_4032:
    ; Original: Bank $02 offset $008032
    ; 1440 tiles (23051 bytes)
    INCBIN "gfx/bank_02_008032.png"

Graphics_02_424E:
    ; Original: Bank $02 offset $00824E
    ; 1440 tiles (23044 bytes)
    INCBIN "gfx/bank_02_00824E.png"

Graphics_02_4254:
    ; Original: Bank $02 offset $008254
    ; 1440 tiles (23055 bytes)
    INCBIN "gfx/bank_02_008254.png"

Graphics_02_4260:
    ; Original: Bank $02 offset $008260
    ; 1440 tiles (23046 bytes)
    INCBIN "gfx/bank_02_008260.png"

Graphics_02_4266:
    ; Original: Bank $02 offset $008266
    ; 1441 tiles (23057 bytes)
    INCBIN "gfx/bank_02_008266.png"

Graphics_02_426C:
    ; Original: Bank $02 offset $00826C
    ; 1440 tiles (23040 bytes)
    INCBIN "gfx/bank_02_00826C.png"

Graphics_02_427E:
    ; Original: Bank $02 offset $00827E
    ; 1440 tiles (23042 bytes)
    INCBIN "gfx/bank_02_00827E.png"

Graphics_02_4284:
    ; Original: Bank $02 offset $008284
    ; 1440 tiles (23050 bytes)
    INCBIN "gfx/bank_02_008284.png"

Graphics_02_429C:
    ; Original: Bank $02 offset $00829C
    ; 1440 tiles (23045 bytes)
    INCBIN "gfx/bank_02_00829C.png"

Graphics_02_42AE:
    ; Original: Bank $02 offset $0082AE
    ; 1440 tiles (23047 bytes)
    INCBIN "gfx/bank_02_0082AE.png"

Graphics_02_42B4:
    ; Original: Bank $02 offset $0082B4
    ; 1440 tiles (23048 bytes)
    INCBIN "gfx/bank_02_0082B4.png"

Graphics_02_42CC:
    ; Original: Bank $02 offset $0082CC
    ; 1440 tiles (23040 bytes)
    INCBIN "gfx/bank_02_0082CC.png"

Graphics_02_42DE:
    ; Original: Bank $02 offset $0082DE
    ; 1440 tiles (23042 bytes)
    INCBIN "gfx/bank_02_0082DE.png"

Graphics_02_42E4:
    ; Original: Bank $02 offset $0082E4
    ; 1440 tiles (23053 bytes)
    INCBIN "gfx/bank_02_0082E4.png"

Graphics_02_42F0:
    ; Original: Bank $02 offset $0082F0
    ; 1440 tiles (23044 bytes)
    INCBIN "gfx/bank_02_0082F0.png"

Graphics_02_4548:
    ; Original: Bank $02 offset $008548
    ; 1440 tiles (23043 bytes)
    INCBIN "gfx/bank_02_008548.png"

Graphics_02_454E:
    ; Original: Bank $02 offset $00854E
    ; 1441 tiles (23056 bytes)
    INCBIN "gfx/bank_02_00854E.png"

Graphics_02_4554:
    ; Original: Bank $02 offset $008554
    ; 1440 tiles (23040 bytes)
    INCBIN "gfx/bank_02_008554.png"

Graphics_02_455A:
    ; Original: Bank $02 offset $00855A
    ; 1440 tiles (23045 bytes)
    INCBIN "gfx/bank_02_00855A.png"

Graphics_02_4560:
    ; Original: Bank $02 offset $008560
    ; 1440 tiles (23040 bytes)
    INCBIN "gfx/bank_02_008560.png"

Graphics_02_456C:
    ; Original: Bank $02 offset $00856C
    ; 1440 tiles (23044 bytes)
    INCBIN "gfx/bank_02_00856C.png"

Graphics_02_4578:
    ; Original: Bank $02 offset $008578
    ; 1440 tiles (23044 bytes)
    INCBIN "gfx/bank_02_008578.png"

Graphics_02_457E:
    ; Original: Bank $02 offset $00857E
    ; 1440 tiles (23046 bytes)
    INCBIN "gfx/bank_02_00857E.png"

Graphics_02_4584:
    ; Original: Bank $02 offset $008584
    ; 1440 tiles (23044 bytes)
    INCBIN "gfx/bank_02_008584.png"

Graphics_02_458A:
    ; Original: Bank $02 offset $00858A
    ; 1440 tiles (23046 bytes)
    INCBIN "gfx/bank_02_00858A.png"

Graphics_02_4590:
    ; Original: Bank $02 offset $008590
    ; 1440 tiles (23048 bytes)
    INCBIN "gfx/bank_02_008590.png"

Graphics_02_45A8:
    ; Original: Bank $02 offset $0085A8
    ; 1440 tiles (23048 bytes)
    INCBIN "gfx/bank_02_0085A8.png"

Graphics_02_45C0:
    ; Original: Bank $02 offset $0085C0
    ; 1440 tiles (23052 bytes)
    INCBIN "gfx/bank_02_0085C0.png"

Graphics_02_45D8:
    ; Original: Bank $02 offset $0085D8
    ; 1441 tiles (23056 bytes)
    INCBIN "gfx/bank_02_0085D8.png"

Graphics_02_45F0:
    ; Original: Bank $02 offset $0085F0
    ; 1441 tiles (23056 bytes)
    INCBIN "gfx/bank_02_0085F0.png"

Graphics_02_46FE:
    ; Original: Bank $02 offset $0086FE
    ; 1440 tiles (23055 bytes)
    INCBIN "gfx/bank_02_0086FE.png"

Graphics_02_4F5F:
    ; Original: Bank $02 offset $008F5F
    ; 1440 tiles (23044 bytes)
    INCBIN "gfx/bank_02_008F5F.png"

Graphics_02_5536:
    ; Original: Bank $02 offset $009536
    ; 1440 tiles (23048 bytes)
    INCBIN "gfx/bank_02_009536.png"

Graphics_02_5572:
    ; Original: Bank $02 offset $009572
    ; 1440 tiles (23052 bytes)
    INCBIN "gfx/bank_02_009572.png"

Graphics_02_5716:
    ; Original: Bank $02 offset $009716
    ; 1440 tiles (23051 bytes)
    INCBIN "gfx/bank_02_009716.png"

Graphics_02_572E:
    ; Original: Bank $02 offset $00972E
    ; 1440 tiles (23048 bytes)
    INCBIN "gfx/bank_02_00972E.png"

Graphics_02_5746:
    ; Original: Bank $02 offset $009746
    ; 1440 tiles (23045 bytes)
    INCBIN "gfx/bank_02_009746.png"

Graphics_02_575E:
    ; Original: Bank $02 offset $00975E
    ; 1440 tiles (23041 bytes)
    INCBIN "gfx/bank_02_00975E.png"

Graphics_02_5A16:
    ; Original: Bank $02 offset $009A16
    ; 1440 tiles (23048 bytes)
    INCBIN "gfx/bank_02_009A16.png"

Graphics_02_5A2E:
    ; Original: Bank $02 offset $009A2E
    ; 1440 tiles (23045 bytes)
    INCBIN "gfx/bank_02_009A2E.png"

Graphics_02_5A46:
    ; Original: Bank $02 offset $009A46
    ; 1440 tiles (23048 bytes)
    INCBIN "gfx/bank_02_009A46.png"

Graphics_02_5A76:
    ; Original: Bank $02 offset $009A76
    ; 1440 tiles (23053 bytes)
    INCBIN "gfx/bank_02_009A76.png"

Graphics_02_5A8E:
    ; Original: Bank $02 offset $009A8E
    ; 1441 tiles (23056 bytes)
    INCBIN "gfx/bank_02_009A8E.png"

Graphics_02_5AA6:
    ; Original: Bank $02 offset $009AA6
    ; 1440 tiles (23046 bytes)
    INCBIN "gfx/bank_02_009AA6.png"

Graphics_02_5ABE:
    ; Original: Bank $02 offset $009ABE
    ; 1440 tiles (23043 bytes)
    INCBIN "gfx/bank_02_009ABE.png"

Graphics_02_5ACA:
    ; Original: Bank $02 offset $009ACA
    ; 1440 tiles (23050 bytes)
    INCBIN "gfx/bank_02_009ACA.png"

Graphics_02_5AD6:
    ; Original: Bank $02 offset $009AD6
    ; 1440 tiles (23046 bytes)
    INCBIN "gfx/bank_02_009AD6.png"

Graphics_02_5AFA:
    ; Original: Bank $02 offset $009AFA
    ; 1440 tiles (23050 bytes)
    INCBIN "gfx/bank_02_009AFA.png"

Graphics_02_5B1E:
    ; Original: Bank $02 offset $009B1E
    ; 1440 tiles (23054 bytes)
    INCBIN "gfx/bank_02_009B1E.png"

Graphics_02_5B42:
    ; Original: Bank $02 offset $009B42
    ; 1440 tiles (23040 bytes)
    INCBIN "gfx/bank_02_009B42.png"

Graphics_02_5B66:
    ; Original: Bank $02 offset $009B66
    ; 1440 tiles (23040 bytes)
    INCBIN "gfx/bank_02_009B66.png"

Graphics_02_5B7E:
    ; Original: Bank $02 offset $009B7E
    ; 1440 tiles (23052 bytes)
    INCBIN "gfx/bank_02_009B7E.png"

Graphics_02_669A:
    ; Original: Bank $02 offset $00A69A
    ; 1440 tiles (23044 bytes)
    INCBIN "gfx/bank_02_00A69A.png"

Graphics_02_66A6:
    ; Original: Bank $02 offset $00A6A6
    ; 1440 tiles (23043 bytes)
    INCBIN "gfx/bank_02_00A6A6.png"

Graphics_02_66CA:
    ; Original: Bank $02 offset $00A6CA
    ; 1440 tiles (23055 bytes)
    INCBIN "gfx/bank_02_00A6CA.png"

Graphics_02_66FA:
    ; Original: Bank $02 offset $00A6FA
    ; 1440 tiles (23049 bytes)
    INCBIN "gfx/bank_02_00A6FA.png"

Graphics_02_6706:
    ; Original: Bank $02 offset $00A706
    ; 1440 tiles (23043 bytes)
    INCBIN "gfx/bank_02_00A706.png"

Graphics_02_6BAA:
    ; Original: Bank $02 offset $00ABAA
    ; 1441 tiles (23056 bytes)
    INCBIN "gfx/bank_02_00ABAA.png"

Graphics_02_6BDA:
    ; Original: Bank $02 offset $00ABDA
    ; 1440 tiles (23048 bytes)
    INCBIN "gfx/bank_02_00ABDA.png"

Graphics_02_6BE6:
    ; Original: Bank $02 offset $00ABE6
    ; 1440 tiles (23048 bytes)
    INCBIN "gfx/bank_02_00ABE6.png"

Graphics_02_6C0A:
    ; Original: Bank $02 offset $00AC0A
    ; 1440 tiles (23053 bytes)
    INCBIN "gfx/bank_02_00AC0A.png"

Graphics_02_6C3A:
    ; Original: Bank $02 offset $00AC3A
    ; 1440 tiles (23040 bytes)
    INCBIN "gfx/bank_02_00AC3A.png"

Graphics_02_6C46:
    ; Original: Bank $02 offset $00AC46
    ; 1440 tiles (23053 bytes)
    INCBIN "gfx/bank_02_00AC46.png"

Graphics_02_6C6A:
    ; Original: Bank $02 offset $00AC6A
    ; 1440 tiles (23040 bytes)
    INCBIN "gfx/bank_02_00AC6A.png"

Graphics_02_6C70:
    ; Original: Bank $02 offset $00AC70
    ; 1440 tiles (23054 bytes)
    INCBIN "gfx/bank_02_00AC70.png"

Graphics_02_6C76:
    ; Original: Bank $02 offset $00AC76
    ; 1440 tiles (23051 bytes)
    INCBIN "gfx/bank_02_00AC76.png"

Graphics_03_78F0:
    ; Original: Bank $03 offset $00F8F0
    ; 272 tiles (4357 bytes)
    INCBIN "gfx/bank_03_00F8F0.png"

Graphics_03_7DC5:
    ; Original: Bank $03 offset $00FDC5
    ; 3854 tiles (61669 bytes)
    INCBIN "gfx/bank_03_00FDC5.png"

Graphics_03_7DE2:
    ; Original: Bank $03 offset $00FDE2
    ; 240 tiles (3845 bytes)
    INCBIN "gfx/bank_03_00FDE2.png"

Graphics_03_7E3E:
    ; Original: Bank $03 offset $00FE3E
    ; 113 tiles (1809 bytes)
    INCBIN "gfx/bank_03_00FE3E.png"

Graphics_03_7E5A:
    ; Original: Bank $03 offset $00FE5A
    ; 112 tiles (1795 bytes)
    INCBIN "gfx/bank_03_00FE5A.png"

Graphics_04_5D81:
    ; Original: Bank $04 offset $011D81
    ; 145 tiles (2327 bytes)
    INCBIN "gfx/bank_04_011D81.png"

Graphics_06_6163:
    ; Original: Bank $06 offset $01A163
    ; 48 tiles (769 bytes)
    INCBIN "gfx/bank_06_01A163.png"

Graphics_07_6414:
    ; Original: Bank $07 offset $01E414
    ; 385 tiles (6161 bytes)
    INCBIN "gfx/bank_07_01E414.png"

Graphics_07_727D:
    ; Original: Bank $07 offset $01F27D
    ; 289 tiles (4630 bytes)
    INCBIN "gfx/bank_07_01F27D.png"

Graphics_08_5D86:
    ; Original: Bank $08 offset $021D86
    ; 273 tiles (4369 bytes)
    INCBIN "gfx/bank_08_021D86.png"

Graphics_0B_4575:
    ; Original: Bank $0B offset $02C575
    ; 904 tiles (14466 bytes)
    INCBIN "gfx/bank_0B_02C575.png"

Graphics_0B_67DC:
    ; Original: Bank $0B offset $02E7DC
    ; 257 tiles (4113 bytes)
    INCBIN "gfx/bank_0B_02E7DC.png"

Graphics_0E_5F09:
    ; Original: Bank $0E offset $039F09
    ; 112 tiles (1802 bytes)
    INCBIN "gfx/bank_0E_039F09.png"

